ParkBundle\Entity\Computer:
    properties:
        name:
            - NotBlank: ~
            - Length:
                min: 3
                max: 50
        ip:
            - NotBlank: ~
            - Ip: ~
        person:
            - NotBlank: ~

ParkBundle\Entity\Person:
    properties:
        name:
            - NotBlank: ~
            - Length:
                min: 3
                max: 50
        firstname:
            - NotBlank: ~
            - Length:
                min: 3
                max: 50