ParkBundle\Entity\Computer:
    type: entity
    table: computer

    id:
        id:
            type: integer
            generator: { strategy: AUTO }

    fields:
        name:
            type: string
            length: 40
        ip:
            type: string
            length: 15
        enabled:
            type: boolean

    manyToOne:
        person:
            targetEntity: Person
            inversedBy: computers
            joinColumn:
                name: person_id
                referencedColumnName: id
